[package]
name = "device-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Sylvain Oliver"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4" }