Writable:
  LogLevel: INFO

Service:
  Port: 59988
  StartupMsg: "Simulation device service started"

Clients:
  core-metadata:
    Host: localhost
    Port: 59881

Device:
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"


MessageBus:
  Protocol: redis
  Host: localhost
  Port: 6379
  Type: redis
  AuthMode: "usernamepassword"  # required for redis messagebus (secure or insecure)
  SecretName: redisdb
  Optional:
    ClientId: device-simulation