name: PR CI
run-name: "[PR CI] ${{ github.head_ref }} -> ${{ github.base_ref }} :rocket:"
on: [pull_request]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Generate Open Api
        run: ./generate_api.sh
      - name: Create build environment
        uses: docker/build-push-action@v5
        with:
          push: false
          target: build_env
          tags: build_env:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: "Run cargo test in build environment"
        uses: addnab/docker-run-action@v3
        with:
          image: build_env:latest
          options: -v ${{ github.workspace }}:/src
          run: |
            NEXTEST_PROFILE=ci cargo llvm-cov --no-report nextest
            cargo llvm-cov report --lcov --output-path lcov.info
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: target/nextest/ci/junit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

